### ISSUE TITLE
Documentation/Starter guide

### ISSUE THREAD

**Issue by Dankerprouduct** [rzander/sccmclictrlib#9]
Hello, I was wondering if there will be any documentation on how to start using this library or a quick start guide sometime in the future?

**Comment by rzander** [comment]
sure, sometime in the future ...
You can use the source from https://github.com/rzander/sccmclictr to check how to use this library...
Do  you have some specific questions?

**Comment by Dankerprouduct** [comment]
No, not any right now. Thank you for your quick response!
